### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by 1in9ui5t** [WojciechZankowski/iextrading4j#29]
**Describe the bug**
The first time I execute a request using the IEXTradingClient, it throws this exception. Subsequent requests do not throw the same exception. Regardless of whether the exception is thrown, the request succeeds. I'm utilizing the SymbolsRequestBuilder though i don't think that matters. This is being triggered in a Spring Boot application by running as a Java process, not in an application server.

**To Reproduce**
`final IEXTradingClient iexTradingClient = IEXTradingClient.create();
final List<ExchangeSymbol> exchangeSymbolList = iexTradingClient.executeRequest(new SymbolsRequestBuilder().build());`
Review log output ([stack trace](https://github.com/WojciechZankowski/iextrading4j/files/2242441/scratch_3.txt))

**Expected behavior**
No exception in log output

**Additional context**
The request is triggered by a REST endpoint `@Async` Resource handler.

**Comment by WojciechZankowski** [comment]
Hey,

It looks like some problem with your environment configuration.


That's a root cause:

```
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
```

It is hard for me to say what's the problem on your side, but you can check for solutions here:

https://www.google.com/search?q=java.lang.reflect.InvocationTargetException%3A+null+%09at+sun.reflect.NativeMethodAccessorImpl.invoke0(Native+Method)&oq=java.lang.reflect.InvocationTargetException%3A+null+%09at+sun.reflect.NativeMethodAccessorImpl.invoke0(Native+Method)


Thanks,

Wojtek
