### ISSUE TITLE
How does the new websocket for TOP work?

### ISSUE THREAD

**Issue by rmantovani** [WojciechZankowski/iextrading4j#54]
## Summary
TOP TopsAsyncRequestBuilder works until yesterday (2019-06-17), Today is not working:

        final IEXTradingClient iexTradingClient = IEXTradingClient.create();
        final Consumer<TOPS> TOPS_CONSUMER = this::doTradingTops;
        final SocketRequest<TOPS> request = new TopsAsyncRequestBuilder()
                .withAllSymbols()
                .build();
        iexTradingClient.unsubscribe(request);
        iexTradingClient.subscribe(request, TOPS_CONSUMER);

How does the new websocket for TOP work?

### Date/time of issue
2019-06-18

### What you expected to happen

Websocket works

### What actually happened

Websocket dont return anything

**Comment by WojciechZankowski** [comment]
Hey,

Request for all symbols from TOPS doesn't work anymore since June 15 according to Sunset Schedule from IEX API https://iextrading.com/developer/  Although you can still use old API to request TOPS data for single symbols. 

I didn't add support for new streaming API in IEX Cloud yet. I will add it, but it is not free anymore. https://iexcloud.io/docs/api/#streaming

Cheers,

Wojtek
